name: Comment on Jira Issue from Commit

on:
  push:
    branches:
      - dev

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get commit message
        id: get_commit
        run: |
          COMMIT_MSG=$(git log -1 --pretty=%B)
          echo "COMMIT_MSG=$COMMIT_MSG" >> $GITHUB_ENV
          echo "Debug: Full commit message: $COMMIT_MSG"
          
          ISSUE_KEY=$(echo "$COMMIT_MSG" | grep -oE 'GJ-?[0-9]+' | head -1 || true)
          echo "ISSUE_KEY=$ISSUE_KEY" >> $GITHUB_ENV
          echo "Debug: Extracted JIRA key: '$ISSUE_KEY'"
          
          if [ -z "$ISSUE_KEY" ]; then
            echo "Debug: No JIRA ticket found in commit message"
          else
            echo "Debug: Found JIRA ticket: $ISSUE_KEY"
          fi

      - name: Comment on Jira
        if: env.ISSUE_KEY != ''
        run: |
          echo "Debug: Commenting on JIRA ticket: ${{ env.ISSUE_KEY }}"
          echo "Debug: Commit SHA: ${{ github.sha }}"
          echo "Debug: Actor: ${{ github.actor }}"
          
          RESPONSE=$(curl -s -w "%{http_code}" -X POST \
            -H "Authorization: Basic $(echo -n ${{ secrets.JIRA_EMAIL }}:${{ secrets.JIRA_API_TOKEN }} | base64)" \
            -H "Content-Type: application/json" \
            --data "{\"body\": \"Commit ${{ github.sha }} by ${{ github.actor }}: ${{ env.COMMIT_MSG }}\"}" \
            "${{ secrets.JIRA_BASE_URL }}/rest/api/3/issue/${{ env.ISSUE_KEY }}/comment")
          
          HTTP_CODE=$(echo "$RESPONSE" | tail -c 4)
          BODY=$(echo "$RESPONSE" | head -c -4)
          
          echo "Debug: HTTP Status: $HTTP_CODE"
          echo "Debug: Response: $BODY"
          
          if [ "$HTTP_CODE" -ge 200 ] && [ "$HTTP_CODE" -lt 300 ]; then
            echo "✅ Successfully commented on JIRA ticket ${{ env.ISSUE_KEY }}"
          else
            echo "❌ Failed to comment on JIRA ticket. HTTP Status: $HTTP_CODE"
            echo "Response: $BODY"
            exit 1
          fi
