name: Comment on Jira Issue from Commit

on:
  push:
    branches:
      - dev

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get commit message
        id: get_commit
        run: |
          COMMIT_MSG=$(git log -1 --pretty=%B)
          echo "COMMIT_MSG=$COMMIT_MSG" >> $GITHUB_ENV
          
          # Extract all JIRA ticket references (case-insensitive)
          ISSUE_KEYS=$(echo "$COMMIT_MSG" | grep -oiE 'gj-?[0-9]+' | tr '[:lower:]' '[:upper:]' | sort -u | tr '\n' ',' | sed 's/,$//' || true)
          echo "ISSUE_KEYS=$ISSUE_KEYS" >> $GITHUB_ENV
          
          if [ -n "$ISSUE_KEYS" ]; then
            echo "Found JIRA tickets: $ISSUE_KEYS"
          fi

      - name: Comment on Jira
        if: env.ISSUE_KEYS != ''
        run: |
          # Get secrets
          JIRA_EMAIL_SECRET="${{ secrets.JIRA_EMAIL }}"
          JIRA_TOKEN_SECRET="${{ secrets.JIRA_API_TOKEN }}"
          JIRA_BASE_SECRET="${{ secrets.JIRA_BASE_URL }}"
          
          # Quick secret validation
          if [ -z "$JIRA_EMAIL_SECRET" ] || [ -z "$JIRA_TOKEN_SECRET" ] || [ -z "$JIRA_BASE_SECRET" ]; then
            echo "❌ Missing JIRA secrets. Check organization secrets: JIRA_EMAIL, JIRA_API_TOKEN, JIRA_BASE_URL"
            exit 1
          fi
          
          # Clean base URL
          JIRA_BASE_CLEAN=$(echo "$JIRA_BASE_SECRET" | sed 's/\/$//')
          
          # Process tickets and post comments
          IFS=',' read -ra TICKET_ARRAY <<< "${{ env.ISSUE_KEYS }}"
          VALID_TICKETS=""
          
          for ISSUE_KEY in "${TICKET_ARRAY[@]}"; do
            ISSUE_KEY=$(echo "$ISSUE_KEY" | tr -d ' ')
            [ -z "$ISSUE_KEY" ] && continue
            
            # Quick ticket validation with timeout
            if timeout 10 curl -sf -u "$JIRA_EMAIL_SECRET:$JIRA_TOKEN_SECRET" \
               "$JIRA_BASE_CLEAN/rest/api/3/issue/$ISSUE_KEY" >/dev/null 2>&1; then
              
              echo "✅ $ISSUE_KEY accessible"
              VALID_TICKETS="${VALID_TICKETS:+$VALID_TICKETS,}$ISSUE_KEY"
            else
              echo "⚠️ $ISSUE_KEY not accessible"
            fi
          done
          
          [ -z "$VALID_TICKETS" ] && { echo "❌ No valid tickets found"; exit 1; }
          
          # Create JIRA comment with clickable links
          COMMIT_MESSAGE="${{ env.COMMIT_MSG }}"
          
          # Create base comment structure
          JIRA_PAYLOAD="{\"body\": {\"type\": \"doc\", \"version\": 1, \"content\": [{\"type\": \"paragraph\", \"content\": ["
          JIRA_PAYLOAD="${JIRA_PAYLOAD}{\"type\": \"text\", \"text\": \"🚀 Commit \"},"
          JIRA_PAYLOAD="${JIRA_PAYLOAD}{\"type\": \"text\", \"text\": \"${{ github.sha }}\", \"marks\": [{\"type\": \"code\"}]},"
          JIRA_PAYLOAD="${JIRA_PAYLOAD}{\"type\": \"text\", \"text\": \" by ${{ github.actor }}\\n\\n🔗 Repository: \"},"
          JIRA_PAYLOAD="${JIRA_PAYLOAD}{\"type\": \"text\", \"text\": \"${{ github.repository }}\", \"marks\": [{\"type\": \"link\", \"attrs\": {\"href\": \"https://github.com/${{ github.repository }}\"}}]},"
          JIRA_PAYLOAD="${JIRA_PAYLOAD}{\"type\": \"text\", \"text\": \"\\n\\n💬 Referenced tickets: \"}"
          
          # Add ticket links
          IFS=',' read -ra VALID_TICKET_ARRAY <<< "$VALID_TICKETS"
          FIRST_TICKET=true
          for ISSUE_KEY in "${VALID_TICKET_ARRAY[@]}"; do
            ISSUE_KEY=$(echo "$ISSUE_KEY" | tr -d ' ')
            if [ "$FIRST_TICKET" = true ]; then
              FIRST_TICKET=false
            else
              JIRA_PAYLOAD="${JIRA_PAYLOAD},{\"type\": \"text\", \"text\": \", \"}"
            fi
            JIRA_PAYLOAD="${JIRA_PAYLOAD},{\"type\": \"text\", \"text\": \"$ISSUE_KEY\", \"marks\": [{\"type\": \"link\", \"attrs\": {\"href\": \"$JIRA_BASE_CLEAN/browse/$ISSUE_KEY\"}}]}"
          done
          
          # Add commit message
          ESCAPED_COMMIT=$(echo "$COMMIT_MESSAGE" | sed 's/"/\\"/g' | sed 's/\\/\\\\/g')
          JIRA_PAYLOAD="${JIRA_PAYLOAD},{\"type\": \"text\", \"text\": \"\\n\\nCommit message: $ESCAPED_COMMIT\"}"
          
          # Close the JSON structure
          JIRA_PAYLOAD="${JIRA_PAYLOAD}]}]}}"
          
          # Post comments to valid tickets
          IFS=',' read -ra VALID_TICKET_ARRAY <<< "$VALID_TICKETS"
          for ISSUE_KEY in "${VALID_TICKET_ARRAY[@]}"; do
            ISSUE_KEY=$(echo "$ISSUE_KEY" | tr -d ' ')
            
            if timeout 15 curl -sf -X POST -u "$JIRA_EMAIL_SECRET:$JIRA_TOKEN_SECRET" \
               -H "Content-Type: application/json" \
               --data "$JIRA_PAYLOAD" \
               "$JIRA_BASE_CLEAN/rest/api/3/issue/$ISSUE_KEY/comment" >/dev/null 2>&1; then
              echo "✅ Commented on $ISSUE_KEY"
            else
              echo "⚠️ Failed to comment on $ISSUE_KEY"
            fi
          done
