- name: Comment on Jira
  if: env.ISSUE_KEYS != ''
  run: |
    JIRA_EMAIL_SECRET="${{ secrets.JIRA_EMAIL }}"
    JIRA_TOKEN_SECRET="${{ secrets.JIRA_API_TOKEN }}"
    JIRA_BASE_SECRET="${{ secrets.JIRA_BASE_URL }}"
    
    if [ -z "$JIRA_EMAIL_SECRET" ] || [ -z "$JIRA_TOKEN_SECRET" ] || [ -z "$JIRA_BASE_SECRET" ]; then
      echo "❌ Missing JIRA secrets"
      exit 1
    fi
    
    JIRA_BASE_CLEAN=$(echo "$JIRA_BASE_SECRET" | sed 's/\/$//')
    
    IFS=',' read -ra TICKET_ARRAY <<< "${{ env.ISSUE_KEYS }}"
    VALID_TICKETS=""
    
    for ISSUE_KEY in "${TICKET_ARRAY[@]}"; do
      ISSUE_KEY=$(echo "$ISSUE_KEY" | tr -d ' ')
      [ -z "$ISSUE_KEY" ] && continue
      
      if curl --fail --silent --max-time 10 -u "$JIRA_EMAIL_SECRET:$JIRA_TOKEN_SECRET" \
         "$JIRA_BASE_CLEAN/rest/api/3/issue/$ISSUE_KEY" >/dev/null 2>&1; then
        echo "✅ $ISSUE_KEY accessible"
        VALID_TICKETS="${VALID_TICKETS:+$VALID_TICKETS,}$ISSUE_KEY"
      else
        echo "⚠️ $ISSUE_KEY not accessible"
      fi
    done
    
    [ -z "$VALID_TICKETS" ] && { echo "❌ No valid tickets found"; exit 1; }
    
    ESCAPED_COMMIT=$(echo "${{ env.COMMIT_MSG }}" | sed 's/"/\\"/g' | tr '\n' ' ')
    
    IFS=',' read -ra VALID_TICKET_ARRAY <<< "$VALID_TICKETS"
    for ISSUE_KEY in "${VALID_TICKET_ARRAY[@]}"; do
      ISSUE_KEY=$(echo "$ISSUE_KEY" | tr -d ' ')
      
      echo "🔄 Posting comment to $ISSUE_KEY..."
      
      curl --fail --silent --show-error --max-time 15 -X POST \
        -u "$JIRA_EMAIL_SECRET:$JIRA_TOKEN_SECRET" \
        -H "Content-Type: application/json" \
        -H "Accept: application/json" \
        --data "{
          \"body\": {
            \"type\": \"doc\",
            \"version\": 1,
            \"content\": [{
              \"type\": \"paragraph\",
              \"content\": [
                {\"type\": \"text\", \"text\": \"🚀 Commit ${GITHUB_SHA} by ${GITHUB_ACTOR}\\n\\n🔗 Repository: https://github.com/${GITHUB_REPOSITORY}\\n\\n💬 $ESCAPED_COMMIT\"}
              ]
            }]
          }
        }" \
        "$JIRA_BASE_CLEAN/rest/api/3/issue/$ISSUE_KEY/comment"
      
      if [ $? -eq 0 ]; then
        echo "✅ Successfully commented on $ISSUE_KEY"
      else
        echo "⚠️ Failed to comment on $ISSUE_KEY"
      fi
    done
